pages:
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install -r requirements.txt
  - pdoc --html --output-dir public medcam
  artifacts:
    paths:
    - public